if(NOT WIN32 OR DEFINED ENV{WT_SESSION} OR CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
	string(ASCII 27 Esc)
	set(ColorReset      "${Esc}[m")
	set(Bold            "${Esc}[1m")
	set(Red             "${Esc}[31m")
	set(Green           "${Esc}[32m")
	set(Yellow          "${Esc}[33m")
	set(Blue            "${Esc}[34m")
	set(Magenta         "${Esc}[35m")
	set(Cyan            "${Esc}[36m")
	set(White           "${Esc}[37m")
	set(BoldRed         "${Esc}[1;31m")
	set(BoldGreen       "${Esc}[1;32m")
	set(BoldYellow      "${Esc}[1;33m")
	set(BoldBlue        "${Esc}[1;34m")
	set(BoldMagenta     "${Esc}[1;35m")
	set(BoldCyan        "${Esc}[1;36m")
	set(BoldWhite       "${Esc}[1;37m")
endif()

function(message_color color msg)
	message( "${color}${msg}${ColorReset}")
endfunction()